# Generated by Django 4.0.4 on 2022-04-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_remove_user_image_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
